info:
  contact:
    email: plazas@janelia.hhmi.org
    name: Stephen Plaza
  description: |-
    REST interface for neuPrint.  To test out the interface, copy  your token
    under your acocunt information. Then authorize Swagger by typing "Bearer " and
    pasting the token.
  title: neuprint API
  version: 0.1.0
paths:
  /api/custom/custom:
    get:
      description: Endpoint expects valid cypher and returns rows of data.
      operationId: custom
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            cypher:
              description: cypher statement (read only)
              example: MATCH (n) RETURN n limit 1
              type: string
            version:
              description: specify a neuprint model version for explicit check
              example: 0.5.0
              type: string
          required:
          - cypher
          type: object
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              columns:
                description: Name of each result column
                example:
                - name
                - size
                items:
                  type: string
                type: array
              data:
                description: Table of results
                example:
                - - t4
                  - 323131
                - - mi1
                  - 232323
                items:
                  description: Table row
                  items:
                    description: Cell value
                    type: "null"
                  type: array
                type: array
            type: object
      security:
      - Bearer: []
      summary: Make custom cypher query against the database (read only)
      tags:
      - custom
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
