info:
  contact:
    email: plazas@janelia.hhmi.org
    name: Stephen Plaza
  description: |-
    REST interface for neuPrint.  To test out the interface, copy  your token
    under your acocunt information. Then authorize Swagger by typing "Bearer " and
    pasting the token.
  title: neuprint API
  version: 0.1.0
paths:
  /api/custom/custom:
    get:
      description: Endpoint expects valid cypher and returns rows of data.
      operationId: custom
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            cypher:
              description: cypher statement (read only)
              example: MATCH (n) RETURN n limit 1
              type: string
            version:
              description: specify a neuprint model version for explicit check
              example: 0.5.0
              type: string
          required:
          - cypher
          type: object
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              columns:
                description: Name of each result column
                example:
                - name
                - size
                items:
                  type: string
                type: array
              data:
                description: Table of results
                example:
                - - t4
                  - 323131
                - - mi1
                  - 232323
                items:
                  description: Table row
                  items:
                    description: Cell value
                    type: "null"
                  type: array
                type: array
            type: object
      security:
      - Bearer: []
      summary: Make custom cypher query against the database (read only)
      tags:
      - custom
  /api/dbmeta/database:
    get:
      description: Returns JSON information about the database.
      operationId: getDatabase
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              Description:
                description: Information about the backend
                type: string
              Location:
                description: Server location
                type: string
            type: object
      security:
      - Bearer: []
      summary: Database information
      tags:
      - dbmeta
  /api/dbmeta/datasets:
    get:
      description: Metadata associated with each dataset is also retrieved
      operationId: getDatasets
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              ROIs:
                description: regions of interest available for the dataset
                example:
                - alpha1
                - alpha2
                - alpha3
                items:
                  type: string
                type: array
              last-mod:
                description: Last modification date for dataset
                type: string
              uuid:
                description: last version id for dataset (UUID for DVID)
                type: string
            type: object
      security:
      - Bearer: []
      summary: Gets datasets in the graph database
      tags:
      - dbmeta
  /api/dbmeta/instances:
    get:
      description: |-
        Contains datatype and instance info for data not within the neuprint
        data model.
      operationId: getDataInstances
      responses:
        "200":
          description: successful operation
          schema:
            additionalProperties:
              description: instance type name
              items:
                properties:
                  datasets:
                    items:
                      description: dataset supported by instance
                      type: string
                    type: array
                  instance:
                    description: name of data instance
                    type: string
                type: object
              type: array
            type: object
      security:
      - Bearer: []
      summary: Gets secondary data instances avaiable through neupint http
      tags:
      - dbmeta
  /api/dbmeta/version:
    get:
      description: |-
        Returns the version of the underlying neuprint data model.
        Changes to the minor version not invalidate previous cypher
        queries.
      operationId: getVersion
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              Version:
                type: string
            type: object
      security:
      - Bearer: []
      summary: Gets version of the database
      tags:
      - dbmeta
security:
- Bearer: []
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    scopes:
      admin: Admin scope
      user: User scope
    type: apiKey
swagger: "2.0"
